package com.fintwin.fintwin.goal.domain;

public enum GoalWarningCode {
    ALREADY_ACHIEVABLE,
    EXPENSE_REDUCTION_INFEASIBLE,
    NEGATIVE_INVESTMENT_RETURN,
    INVESTMENT_RETURN_BELOW_DEPOSIT_RATE,
    CASH_SHORTFALL,
    NEGATIVE_AMORTIZATION,
    INCOME_INCREASE_EXCEEDS_CURRENT_INCOME,
    SEARCH_LIMIT_REACHED,
    INVESTMENT_CONTRIBUTION_CASH_LIMITED
}
