package com.fintwin.fintwin.pattern.domain;

public enum PatternWarningCode {
    INSUFFICIENT_HISTORY,
    NO_INCOME_FOUND,
    NO_EXPENSE_FOUND,
    HIGH_INCOME_VOLATILITY,
    HIGH_EXPENSE_VOLATILITY,
    NEGATIVE_CASH_FLOW_MONTHS,
    LOW_SAVINGS_RATE,
    RECURRING_PATTERN_UNAVAILABLE,
    MANY_UNCATEGORIZED_TRANSACTIONS,
    PROFILE_REVIEW_REQUIRED
}
