package com.fintwin.fintwin.ai.openai.error;

public enum AiErrorCode {
    AI_DISABLED,
    AI_CONFIGURATION_INVALID,
    AI_TIMEOUT,
    AI_AUTHENTICATION_FAILED,
    AI_RATE_LIMITED,
    AI_PROVIDER_UNAVAILABLE,
    AI_REFUSED,
    AI_INCOMPLETE_RESPONSE,
    AI_EMPTY_RESPONSE,
    AI_RESPONSE_TOO_LARGE,
    AI_SCHEMA_VIOLATION,
    AI_PRIVACY_GUARD_REJECTED,
    AI_UNKNOWN_ERROR
}
