package com.fintwin.fintwin.agent.domain;

public enum MissingInformationCode {
    START_YEAR_MONTH_REQUIRED,
    HORIZON_REQUIRED,
    ASSUMPTIONS_REQUIRED,
    MONTHLY_DEBT_PAYMENT_REQUIRED,
    EVENTS_REQUIRED,
    EVENT_AMOUNT_REQUIRED,
    EVENT_DATE_REQUIRED,
    EVENT_PERIOD_REQUIRED,
    GOAL_TYPE_REQUIRED,
    TARGET_AMOUNT_REQUIRED
}
