package com.fintwin.fintwin.agent.domain;

public enum RiskCode {
    CASH_SHORTFALL,
    NEGATIVE_AMORTIZATION,
    NET_WORTH_DECREASE,
    LIQUID_ASSET_DECREASE,
    GOAL_NOT_ACHIEVED,
    EXPENSE_REDUCTION_INFEASIBLE,
    INVESTMENT_CONTRIBUTION_CASH_LIMITED
}
